# boot默认配置文件
server:
  port: 8080
# ctrl点击可看具体对应的set方法
spring:
  servlet:
    multipart:
      file-size-threshold: 10MB
  datasource:
    dynamic:
      primary: master # 默认数据源
      strict: false # 严格连接数据源，true：无法链接时报错并使用默认
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/sakila?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
          username: root
          password: mysql
        slave:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/world?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
          username: root
          password: mysql

# mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # logging设置
  mapper-locations: ["classpath*:/mapper/**/*.xml"] # 设xml文件读取路径
  type-aliases-package: ml.java.boot2.**.domain # xml中resultType|paramType对象自动映射为类名
  type-enums-package: ml.java.boot2.**.constant # 枚举标签扫描
# config
user1:
  name: LSP
# demo-starter
baeldung:
  greeter:
    userName: Baeldung
    afternoonMessage: Woha Afternoon